name: Automate Build Docker Image
on:
  workflow_dispatch:
jobs:
  Deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.21"
          cache: true
      - name: Build Binary
        run: |
          go mod download
          GOOS=linux GOARCH=amd64 go build -o bin/main .